const trackArray = [
  {
    track: 'Guilt',
    author: 'Nero',
    album: 'Welcome Reality',
    time: '4:44',
    year: 2011,
    genre: 'dubstep',
    id: 1,
  },
  {
    track: 'Elektro',
    author: 'Dynoro, Outwork, Mr. Gee',
    album: 'Elektro',
    time: '2:23',
    year: 2020,
    genre: 'pop, house',
    id: 2,
  },
  {
    track: 'I’m Fire',
    author: 'Ali Bakgor',
    album: 'I’m Fire',
    time: '2:22',
    year: 2021,
    genre: 'pop, dance',
    id: 3,
  },
  {
    track: 'Non Stop',
    author: 'Стоункат, Psychopath',
    album: 'Non Stop',
    time: '4:12',
    year: 2019,
    genre: 'electronics dubstep',
    id: 4,
  },
  {
    track: 'Run Run',
    together: '(feat. AR/CO)',
    author: 'Jaded, Will Clarke, AR/CO',
    album: 'Run Run',
    time: '2:54',
    year: 2021,
    genre: 'house, dance',
    id: 5,
  },
  {
    track: 'Eyes on Fire',
    together: '(Zeds Dead Remix)',
    author: 'Blue Foundation, Zeds Dead',
    album: 'Eyes on Fire',
    time: '5:20',
    year: 2007,
    genre: 'electronic, dubstep',
    id: 6,
  },
  {
    track: 'Mucho Bien',
    together: '(Hi Profile Remix)',
    author: 'HYBIT, Mr. Black, Offer Nissim, Hi Profile',
    album: 'Mucho Bien',
    time: '3:41',
    year: 2020,
    genre: 'house',
    id: 7,
  },
  {
    track: 'Knives n Cherries',
    author: 'minthaze',
    album: 'Captivating',
    time: '1:48',
    year: 2020,
    genre: 'hip-hop',
    id: 8,
  },
  {
    track: 'How Deep Is Your Love',
    author: 'Calvin Harris, Disciples',
    album: 'How Deep Is Your Love',
    time: '3:32',
    year: 2015,
    genre: 'deep-house',
    id: 9,
  },
  {
    track: 'Morena',
    author: 'Tom Boxer',
    album: 'Soundz Made in Romania',
    time: '3:36',
    year: 2010,
    genre: 'electronic',
    id: 10,
  },
  {
    track: 'Guilt',
    author: 'Nero',
    album: 'Welcome Reality',
    time: '4:44',
    year: 2011,
    genre: 'dubstep',
    id: 11,
  },
  {
    track: 'Elektro',
    author: 'Dynoro, Outwork, Mr. Gee',
    album: 'Elektro',
    time: '2:23',
    year: 2020,
    genre: 'pop, house',
    id: 12,
  },
  {
    track: 'I’m Fire',
    author: 'Ali Bakgor',
    album: 'I’m Fire',
    time: '2:22',
    year: 2021,
    genre: 'pop, dance',
    id: 13,
  },
  {
    track: 'Non Stop',
    author: 'Стоункат, Psychopath',
    album: 'Non Stop',
    time: '4:12',
    year: 2019,
    genre: 'electronics dubstep',
    id: 14,
  },
  {
    track: 'Run Run',
    together: '(feat. AR/CO)',
    author: 'Jaded, Will Clarke, AR/CO',
    album: 'Run Run',
    time: '2:54',
    year: 2021,
    genre: 'house, dance',
    id: 15,
  },
  {
    track: 'Eyes on Fire',
    together: '(Zeds Dead Remix)',
    author: 'Blue Foundation, Zeds Dead',
    album: 'Eyes on Fire',
    time: '5:20',
    year: 2007,
    genre: 'electronic, dubstep',
    id: 16,
  },
  {
    track: 'Mucho Bien',
    together: '(Hi Profile Remix)',
    author: 'HYBIT, Mr. Black, Offer Nissim, Hi Profile',
    album: 'Mucho Bien',
    time: '3:41',
    year: 2020,
    genre: 'house',
    id: 17,
  },
  {
    track: 'Knives n Cherries',
    author: 'minthaze',
    album: 'Captivating',
    time: '1:48',
    year: 2020,
    genre: 'hip-hop',
    id: 18,
  },
  {
    track: 'How Deep Is Your Love',
    author: 'Calvin Harris, Disciples',
    album: 'How Deep Is Your Love',
    time: '3:32',
    year: 2015,
    genre: 'deep-house',
    id: 19,
  },
  {
    track: 'Morena',
    author: 'Tom Boxer',
    album: 'Soundz Made in Romania',
    time: '3:36',
    year: 2010,
    genre: 'electronic',
    id: 20,
  }
]

export default trackArray;
